fixes the trailing zero bytes trimming problem
mymarilyn/clickhouse-driver pull request #283
Opened 2022-01-09 15:03 UTC by xinstein

Addresses #280 

replaces #282

2022-01-10 06:52 UTC, xzkostyan requested changes
We should write test for this bugfix. `tests/numpy/columns/test_string.py` is a good place for it.

2022-01-10 06:52 UTC, xzkostyan commented on clickhouse_driver/columns/numpy/stringcolumn.py
> +        # return np.array(buf.read_strings(n_items), dtype=self.dtype)
What `dtype` was before this fix in array instance?
Do we need this comment?

2022-01-10 13:50 UTC, xinstein commented
I can't run the test case locally due to a lot of importing errors, I looked into some and it's due to my OS (windows10).

2024-02-18 05:42 UTC, xzkostyan commented
Test is not working. Feel free to reopen PR.

2024-02-18 05:42 UTC, closed without merging